version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: job-postgres
    environment:
      POSTGRES_DB: jobsdb
      POSTGRES_USER: jobsuser
      POSTGRES_PASSWORD: jobspass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: job-scheduler-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/jobsdb
      SPRING_DATASOURCE_USERNAME: jobsuser
      SPRING_DATASOURCE_PASSWORD: jobspass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  postgres_data:
